// Generated by CoffeeScript 1.9.3
(function() {
  var associateModels, async, attempt, inflect;

  inflect = require('inflect');

  async = require('async');

  associateModels = function(targetModels, sourceData, sourceModel, next) {
    var processAssociation;
    processAssociation = function(targetModelData, done) {
      var associator, query, ref, targetMethod, targetModel;
      targetModel = sourceModel.sequelize.models[targetModelData.name.singular] || sourceModel.sequelize.models[targetModelData.name.plural];
      associator = sourceModel.associations[targetModelData.name.plural] || sourceModel.associations[targetModelData.name.singular];
      targetMethod = ((ref = associator.accessors) != null ? ref[targetModelData.method] : void 0) || (associator != null ? associator[targetModelData.method] : void 0);
      query = {};
      query.where = {};
      query.where[targetModel.primaryKeyField] = targetModelData.value;
      return targetModel.findAll(query).then(function(targetData) {
        if (typeof targetModelData.value !== 'object') {
          targetData = targetData[0];
        }
        return sourceData[targetMethod](targetData).then(function(res) {
          return done(null, res);
        });
      });
    };
    return async.map(targetModels, processAssociation, function(err, res) {
      return next(null, sourceData);
    });
  };

  attempt = function(sourceModel, sourceData, values, next) {
    var filteredValues, targetModels;
    if (sourceData == null) {
      throw new Error('Attempted to associate with an inexistent resource.');
    }
    filteredValues = Object.keys(values).filter(function(key) {
      var modelName;
      if (key.split('.').length === 2) {
        modelName = key.split('.')[0];
      }
      if (modelName == null) {
        return false;
      }
      return (sourceModel.associations[modelName] != null) || (sourceModel.associations[inflect.pluralize(modelName)] != null);
    });
    targetModels = filteredValues.map(function(value) {
      var data, name, queryValue, ref;
      data = value.split('.');
      name = (ref = sourceModel.associations[data[0]]) != null ? ref.options.name : void 0;
      if (name == null) {
        throw new Error(data[0] + ' does not exist, try singularizing or pluralizing it!');
      }
      try {
        queryValue = JSON.parse(values[value]);
      } catch (_error) {
        queryValue = values[value];
      }
      return {
        name: name,
        method: data[1],
        value: queryValue
      };
    });
    if (targetModels.length === 0) {
      return next(null, sourceData);
    }
    return associateModels(targetModels, sourceData, sourceModel, next);
  };

  module.exports = {
    attempt: attempt
  };

}).call(this);
