// Generated by CoffeeScript 1.8.0
(function() {
  var associateModels, attempt, inflect;

  inflect = require('inflect');

  associateModels = function(targetModels, sourceData, sourceModel, next) {
    var associationCount, tracker;
    associationCount = 1;
    tracker = function(cap) {
      if (associationCount === cap) {
        return next(null, sourceData);
      }
      return associationCount++;
    };
    return targetModels.map(function(targetModelData) {
      var associator, query, targetMethod, targetModel, _ref;
      targetModel = sourceModel.sequelize.models[targetModelData.name.singular];
      associator = sourceModel.associations[targetModelData.name.plural] || sourceModel.associations[targetModelData.name.singular];
      targetMethod = ((_ref = associator.accessors) != null ? _ref[targetModelData.method] : void 0) || (associator != null ? associator[targetModelData.method] : void 0);
      query = {};
      query.where = {};
      query.where[targetModel.primaryKeyField] = targetModelData.value;
      return targetModel.findAll(query).then(function(targetData) {
        if (typeof targetModelData.value !== 'object') {
          targetData = targetData[0];
        }
        return sourceData[targetMethod](targetData).then(function() {
          return tracker(targetModels.length);
        });
      });
    });
  };

  attempt = function(sourceModel, sourceData, values, next) {
    var filteredValues, targetModels;
    if (sourceData == null) {
      throw new Error('Attempted to associate with an inexistent resource.');
    }
    filteredValues = Object.keys(values).filter(function(key) {
      var modelName;
      if (key.split('.').length === 2) {
        modelName = key.split('.')[0];
      }
      if (modelName == null) {
        return false;
      }
      return (sourceModel.associations[modelName] != null) || (sourceModel.associations[inflect.pluralize(modelName)] != null);
    });
    targetModels = filteredValues.map(function(value) {
      var data, name, queryValue, _ref;
      data = value.split('.');
      name = (_ref = sourceModel.associations[data[0]]) != null ? _ref.options.name : void 0;
      if (name == null) {
        throw new Error(data[0] + ' does not exist, try singularizing or pluralizing it!');
      }
      try {
        queryValue = JSON.parse(values[value]);
      } catch (_error) {
        queryValue = values[value];
      }
      return {
        name: name,
        method: data[1],
        value: queryValue
      };
    });
    if (targetModels.length === 0) {
      return next(null, sourceData);
    }
    return associateModels(targetModels, sourceData, sourceModel, next);
  };

  module.exports = {
    attempt: attempt
  };

}).call(this);
