// Generated by CoffeeScript 1.8.0
(function() {
  var _;

  _ = require('underscore');

  module.exports = function() {
    var makeOperation, parseArgumentFunctions, parseArgumentValues, sendResponse;
    sendResponse = function(res, err, data) {
      var headers, response, statusCode;
      response = {};
      if (data) {
        response.data = data;
      }
      statusCode = 200;
      if (err != null) {
        response.error = err;
      }
      headers = {
        'content-type': 'application/json; charset=utf-8'
      };
      return res.set(headers).status(statusCode).end(JSON.stringify(response));
    };
    parseArgumentValues = function(args) {
      return _.values(_.pick(args, function(value) {
        return !_.isFunction(value);
      }));
    };
    parseArgumentFunctions = function(args) {
      return _.values(_.pick(args, function(value) {
        return _.isFunction(value);
      }));
    };
    makeOperation = function(action) {
      var operation;
      return operation = function() {
        var args, oldArgs, sequelizeObject;
        oldArgs = arguments;
        args = parseArgumentValues(arguments);
        args.push(function() {
          var values;
          values = oldArgs;
          if (arguments.length > 0) {
            values = parseArgumentValues(arguments);
            values.push(parseArgumentFunctions(oldArgs)[0]);
          }
          return action.apply(null, values);
        });
        if (operation.before != null) {
          operation.before.apply(null, args);
        }
        if (operation.before == null) {
          sequelizeObject = action.apply(null, arguments);
        }
        if (operation.after != null) {
          return operation.after.call(null, sequelizeObject);
        }
      };
    };
    return {
      sendResponse: sendResponse,
      makeOperation: makeOperation
    };
  };

}).call(this);
