// Generated by CoffeeScript 1.12.0
(function() {
  var BaldError;

  BaldError = (function() {
    function BaldError(name, message) {
      var err;
      this.name = name;
      this.message = message;
      err = new Error(this.message);
      err.name = this.name;
      return err;
    }

    return BaldError;

  })();

  module.exports = BaldError;

}).call(this);
