// Generated by CoffeeScript 1.9.3
(function() {
  var Bald, controller, inflect, manager;

  inflect = require('inflect');

  manager = require('./manager');

  controller = require('./controller');

  Bald = (function() {
    function Bald(arg) {
      var app, sequelize;
      app = arg.app, sequelize = arg.sequelize;
      if ((app == null) || (sequelize == null)) {
        throw new Error('Arguments invalid.');
      }
      this.app = app;
      this.sequelize = sequelize;
    }

    Bald.prototype.resource = function(arg) {
      var eagerLoading, endpoints, middleware, model, modelManager, plural;
      model = arg.model, endpoints = arg.endpoints, middleware = arg.middleware, eagerLoading = arg.eagerLoading;
      if (model == null) {
        throw new Error('Invalid model.');
      }
      if ((endpoints != null) && typeof endpoints !== 'object') {
        throw new Error('Invalid endpoints.');
      }
      endpoints = endpoints || {};
      if ((endpoints.plural == null) && (endpoints.singular == null)) {
        plural = inflect.pluralize(model.name);
        endpoints = {
          plural: '/api/' + plural,
          singular: '/api/' + plural + '/:id'
        };
      }
      modelManager = manager(model, eagerLoading);
      controller(this.app, endpoints, modelManager, middleware);
      return modelManager;
    };

    return Bald;

  })();

  module.exports = Bald;

}).call(this);
