// Generated by CoffeeScript 1.10.0
(function() {
  var Bald, BaldError, controller, inflect, manager;

  inflect = require('inflect');

  manager = require('./manager');

  controller = require('./controller');

  BaldError = require('./error');

  Bald = (function() {
    function Bald(arg) {
      var app;
      app = arg.app;
      if (app == null) {
        throw new BaldError('BaldInitializationError', 'Arguments invalid.');
      }
      this.app = app;
    }

    Bald.prototype.resource = function(arg) {
      var endpoints, hasApi, include, middleware, model, modelManager;
      model = arg.model, endpoints = arg.endpoints, middleware = arg.middleware, include = arg.include, hasApi = arg.hasApi;
      if (hasApi == null) {
        hasApi = true;
      }
      if (model == null) {
        throw new BaldError('BaldResourceError', 'Invalid model.');
      }
      endpoints = endpoints || {};
      if ((endpoints.plural == null) && (endpoints.singular == null)) {
        endpoints = {
          plural: '/api/' + inflect.pluralize(model.name),
          singular: '/api/' + inflect.singularize(model.name + '/:id')
        };
      }
      modelManager = manager(model, include);
      modelManager.model = model;
      if (hasApi) {
        controller(this.app, endpoints, modelManager, middleware);
      }
      return modelManager;
    };

    return Bald;

  })();

  module.exports = Bald;

}).call(this);
