// Generated by CoffeeScript 1.8.0
(function() {
  var Association, async, handleError, makeOperation, _;

  async = require('async');

  _ = require('underscore');

  makeOperation = require('./common').makeOperation;

  Association = require('./association');

  handleError = function(err, next) {
    if (err.name === 'SequelizeValidationError') {
      return next(err, null);
    }
    throw err;
  };

  module.exports = function(model, eagerLoading) {
    var create, del, list, read, update, updateMultiple;
    create = makeOperation(function(values, done) {
      var query;
      query = query || {};
      if (eagerLoading != null) {
        query.include = {
          all: true,
          nested: true
        };
      }
      return async.waterfall([
        function(done) {
          return model.create(values).then(function(data) {
            return Association.attempt(model, data, values, done);
          })["catch"](function(err) {
            return handleError(err, done);
          });
        }, function(data, done) {
          query.where = data.get();
          return model.find(query).then(function(data) {
            return done(null, data);
          });
        }
      ], function(err, data) {
        return done(err, data);
      });
    });
    list = makeOperation(function(options, done) {
      var query;
      query = query || {};
      if (eagerLoading != null) {
        query.include = {
          all: true,
          nested: true
        };
      }
      if ((options.filter != null) && (options.filterBy != null)) {
        query.where = {};
        query.where[options.filterBy] = options.filter;
      }
      if ((options.limit != null) && (options.offset != null)) {
        query.limit = +options.limit;
        query.offset = +options.offset;
      }
      if ((options.sort != null) && (options.sortBy != null)) {
        query.order = options.sortBy + ' ' + options.sort;
      }
      return model.findAll(query).then(function(data) {
        return done(null, data);
      })["catch"](function(err) {
        return handleError(err, done);
      });
    });
    read = makeOperation(function(whereQuery, done) {
      var query;
      query = {
        where: whereQuery
      };
      if (eagerLoading != null) {
        query.include = {
          all: true,
          nested: true
        };
      }
      return model.find(query).then(function(data) {
        return done(null, data);
      })["catch"](function(err) {
        return handleError(err, done);
      });
    });
    update = makeOperation(function(id, values, done) {
      var query, updateValues;
      query = {
        where: {
          id: id
        }
      };
      if (eagerLoading != null) {
        query.include = {
          all: true,
          nested: true
        };
      }
      updateValues = _.omit(values, function(value) {
        return !/\w+.[set|add|remove]+/.test(value);
      });
      return async.waterfall([
        function(done) {
          return model.update(updateValues, query).then(function(data) {
            return done(null);
          })["catch"](function(err) {
            return handleError(err, done);
          });
        }, function(done) {
          return model.find(query).then(function(data) {
            return Association.attempt(model, data, values, function() {
              return done();
            });
          })["catch"](function(err) {
            return handleError(err, done);
          });
        }, function(done) {
          return model.find(query).then(function(data) {
            return done(null, data);
          })["catch"](function(err) {
            return handleError(err, done);
          });
        }
      ], function(err, data) {
        return done(err, data);
      });
    });
    updateMultiple = makeOperation(function(values, done) {
      var updateValue;
      updateValue = function(value, done) {
        return async.waterfall([
          function(done) {
            return model.update(value, {
              where: {
                id: value.id
              }
            }).then(function(data) {
              return done(null);
            })["catch"](function(err) {
              return handleError(err, done);
            });
          }, function(done) {
            var query;
            query = {
              where: {
                id: value.id
              }
            };
            if (eagerLoading != null) {
              query.include = {
                all: true,
                nested: true
              };
            }
            return model.find(query).then(function(data) {
              return done(null, value);
            })["catch"](function(err) {
              return handleError(err, done);
            });
          }
        ], function(err, data) {
          return done(err, data);
        });
      };
      return async.map(values, updateValue, done);
    });
    del = makeOperation(function(id, done) {
      return model.destroy({
        where: {
          id: id
        }
      }).then(function(data) {
        return done(null, data);
      })["catch"](function(err) {
        return handleError(err, done);
      });
    });
    return {
      create: create,
      list: list,
      read: read,
      update: update,
      updateMultiple: updateMultiple,
      del: del
    };
  };

}).call(this);
