// Generated by CoffeeScript 1.10.0
(function() {
  var Bald, BaldError, Controller, _, inflect;

  inflect = require('inflect');

  _ = require('lodash');

  Controller = require('./Controller');

  BaldError = require('./Error');

  Bald = (function() {
    function Bald(arg) {
      var app, knex;
      app = arg.app, knex = arg.knex;
      if (app == null) {
        throw new BaldError('BaldInitializationError', 'Arguments invalid.');
      }
      this.app = app;
      this.knex = knex;
    }

    Bald.prototype.resource = function(arg) {
      var endpoints, middleware, model, primaryKey;
      model = arg.model, primaryKey = arg.primaryKey, endpoints = arg.endpoints, middleware = arg.middleware;
      if (model == null) {
        throw new BaldError('BaldResourceError', 'Invalid model.');
      }
      primaryKey = primaryKey || 'id';
      endpoints = endpoints || {
        plural: '/api/' + inflect.pluralize(model),
        singular: '/api/' + inflect.singularize(model + '/:pk')
      };
      return Controller({
        app: this.app,
        knex: this.knex,
        model: model,
        endpoints: endpoints,
        primaryKey: primaryKey,
        middleware: middleware
      });
    };

    return Bald;

  })();

  module.exports = Bald;

}).call(this);
