// Generated by CoffeeScript 1.10.0
(function() {
  var Bald, BaldError, Controller, _, inflect;

  inflect = require('inflect');

  _ = require('lodash');

  Controller = require('./Controller');

  BaldError = require('./Error');

  Bald = (function() {
    function Bald(arg) {
      var app, knex;
      app = arg.app, knex = arg.knex;
      if (app == null) {
        throw new BaldError('BaldInitializationError', 'Arguments invalid.');
      }
      this.app = app;
      this.knex = knex;
    }

    Bald.prototype.resource = function(arg) {
      var endpoints, middleware, model;
      model = arg.model, endpoints = arg.endpoints, middleware = arg.middleware;
      if (model == null) {
        throw new BaldError('BaldResourceError', 'Invalid model.');
      }
      endpoints = endpoints || {};
      if ((endpoints.plural == null) && (endpoints.singular == null)) {
        endpoints = {
          plural: '/api/' + inflect.pluralize(model),
          singular: '/api/' + inflect.singularize(model + '/:id')
        };
      }
      return Controller({
        app: this.app,
        knex: this.knex,
        model: model,
        endpoints: endpoints,
        middleware: middleware
      });
    };

    return Bald;

  })();

  module.exports = Bald;

}).call(this);
